site_name: maSMP
site_url: https://masmp.com/
nav:
    - 'index.md'
    - 'maSMP_Schema.md'
    - Types:
      - 'Types/OutputManagementPlan.md'
      -  Types/Question.md'
      - 'Types/SoftwareManagementPlan.md'
      - 'Types/SoftwareSourceCode.md'
      - 'Types/SoftwareApplication.md'
      - 'Types/SoftwareRunAction.md'
      - 'Types/SoftwareTestAction.md'
    - 'about.md'
      
    
theme:
  name: material
  
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/zbmed-semtec/maSPMs
    

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html

plugins:
  - search


  

